/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.MainController;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import model.Object;
import utils.HintTextField;
import utils.KonversiMataUang;

/**
 *
 * @author jepe
 */
public class Main extends javax.swing.JFrame {
    
    private MainController mController;
    private Object mObject;
    private KonversiMataUang mKonversiMataUang;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        //instance Class
        mController = new MainController(this);
        mObject = new Object();
        mKonversiMataUang = new KonversiMataUang();
        
        initNilaiAwal();
    }
    
    public void initNilaiAwal(){
        mKonversiMataUang.setMataUang(0);
        String nilai = mKonversiMataUang.getKonversi();
        
//        JTextField edtNilai1 = new HintTextField(nilai);
//        JTextField edtNilai2 = new HintTextField(nilai);
        txtHasil.setText(nilai);
    }
    
    public void showData(Object data){
        String hasil = "";
        
        mKonversiMataUang.setMataUang(data.getHasil());
        hasil = mKonversiMataUang.getKonversi();
        
        txtHasil.setText(hasil);
    }
    
    public void setNumberOnly(char mChar, KeyEvent evt){
        if (!(Character.isDigit(mChar)) || (mChar == KeyEvent.VK_BACK_SPACE) || (mChar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHasil = new javax.swing.JLabel();
        edtNilai1 = new javax.swing.JTextField();
        edtNilai2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        txtHasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHasil.setText("Hello world");

        edtNilai1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtNilai1KeyTyped(evt);
            }
        });

        edtNilai2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtNilai2KeyTyped(evt);
            }
        });

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtNilai2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(edtNilai1))
                        .addGap(18, 18, 18)
                        .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mObject.setA(Double.parseDouble(edtNilai1.getText().toString()));
        mObject.setB(Double.parseDouble(edtNilai2.getText().toString()));
        
        mController.hitung(mObject);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edtNilai1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNilai1KeyTyped
        char mChar = evt.getKeyChar();
        setNumberOnly(mChar, evt);
    }//GEN-LAST:event_edtNilai1KeyTyped

    private void edtNilai2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNilai2KeyTyped
        char mChar = evt.getKeyChar();
        setNumberOnly(mChar, evt);
    }//GEN-LAST:event_edtNilai2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtNilai1;
    private javax.swing.JTextField edtNilai2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtHasil;
    // End of variables declaration//GEN-END:variables
}
